name: Industrialisation continue sur le serveur AWS (Tomcat)
on: push
jobs:
  build:
    name: Package AWS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
          jar cvf CorentinCLERO.war *
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        source: "CorentinCLERO.war"
        target: "/opt/tomcat/webapps"

  deployIPFSMSPR:
    name: SAV IPFS MSPR
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - run: |
          jar cvf fichier.war *
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
      - run: |
          apk add go-ipfs
          ipfs init
          ipfs daemon &
        shell: alpine.sh --root {0}
      - name: Sauvegarde fichier war sur IPFS
        run: |
          ls -la 
          ipfs swarm peers
          ipfs add fichier.war
          IPFS_KEY=$(ipfs add fichier.war -Q)  # Capture de la clé IPFS
          echo $IPFS_KEY > ipfs_key.txt # Écriture de la clé dans un fichier
          echo "Clé IPFS ajoutée : $IPFS_KEY"
        shell: alpine.sh --root {0}
      - name: Notification Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          ipfs_key=$(cat ipfs_key.txt)
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"Le workflow IPFS est terminé. Clé IPFS MSPR : $ipfs_key\"}" $DISCORD_WEBHOOK
